<?php
  $departamentos=[
      "Amazonas"=>"91",
      "Antioquia"=>"05",
      "Arauca"=>"81",
      "Atlantico"=>"08",
      "Bogotá"=>"11",
      "Bolivar"=>"13",
      "Boyaca"=>"15",
      "Caldas"=>"17",
      "Caqueta"=>"18",
      "Casanare"=>"85",
      "Cauca"=>"19",
      "Cesar"=>"20",
      "Choco"=>"27",
      "Cordoba"=>"23",
      "Cundinamarca"=>"25",
      "Guainia"=>"94",
      "Guaviare"=>"95",
      "Huila"=>"41",
      "La Guajira"=>"44",
      "Magdalena"=>"47",
      "Meta"=>"50",
      "Nariño"=>"52",
      "Norte de Santander"=>"54",
      "Putumayo"=>"86",
      "Quindio"=>"63",
      "Risaralda"=>"66",
      "San Andres"=>"88",
      "Santander"=>"68",
      "Sucre"=>"70",
      "Tolima"=>"73",
      "Valle"=>"76",
      "Vaupes"=>"97",
      "Vichada"=>"99"
  ];
?>
